info:
  contact: {}
  license: {}
paths:
  /showaccount:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/string'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/string'
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/404'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/string'
            type: object
      summary: Show a account
      tags:
      - accounts
